# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket   = "my-bucket"
    encrypt  = false
    endpoint = "http://localhost:4566"
    key      = "terragrunted/env/dev/nginx-test-2.tfstate"
    region   = "eu-west-1"


    skip_credentials_validation = true
    skip_metadata_api_check     = true
    force_path_style            = true
    dynamodb_table              = "terraform_state"
    dynamodb_endpoint           = "http://localhost:4566"
  }
}


module "network" {
  source = "../modules/network"

  providers = {
    docker = docker.remote
  }



}


module "backend" {
  source = "../modules/backend"

  providers = {
    docker = docker.remote
  }

  name              = "backend-dev"
  env               = "dev"
  port              = 8087
  docker_network_id = module.network.id

}


module "nginx-test" {

  providers = {
    docker = docker.remote
  }

  depends_on = [
    module.backend
  ]

  source    = "../modules/nginx"
  name      = "test_1"
  port      = 9999
  host      = "10.8.0.1"
  user      = "root"
  path_site = "/home/xi/Projects/devops/aws-local-terraform/tmp/nginx"





  docker_newtork_id = module.network.id
  backend_hostname  = module.backend.docker_ip[0]
  backend_port      = 8087
}
